// Code generated by "stringer -type Token"; DO NOT EDIT

package parser

import "fmt"

const _Token_name = "WhitespaceIntegerTextUnknownEOFSlashOpeningBracketClosingBracketOpeningParentheseClosingParentheseColonDotEqualGoroutinePanicRecoveredRuntimeErrorCreatedByRunningIOWaitChanReceiveSendSyscall"

var _Token_index = [...]uint8{0, 10, 17, 21, 28, 31, 36, 50, 64, 81, 98, 103, 106, 111, 120, 125, 134, 141, 146, 153, 155, 162, 168, 172, 179, 183, 190}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
