// Code generated by "stringer -type Token"; DO NOT EDIT

package parser

import "fmt"

const _Token_name = "WhitespaceNewLineIntegerTextEOFSlashUnknownOpeningBracketClosingBracketOpeningParentheseClosingParentheseColonDotEqualGoroutinePanicRecoveredRuntimeErrorCreatedByRunningIOWaitChanReceiveSendSyscallPointer"

var _Token_index = [...]uint8{0, 10, 17, 24, 28, 31, 36, 43, 57, 71, 88, 105, 110, 113, 118, 127, 132, 141, 148, 153, 160, 162, 169, 175, 179, 186, 190, 197, 204}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
